# Site settings
title: "Chase McDermott's Website"
description: "Welcome to Chase McDermott's personal website." 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Chase McDermott
user_description: "Thanks for visiting my website! I am currently a Junior at Texas A&M, and am very excited and passionate about Software Engineering. I love to learn new things every single day. My best language currently is C++, and I have a few projects below that are written in C++. I also am familiar with Python and plan to learn Java soon as well. Check out my Resume above, or some of my projects below!"
baseurl: ""
user_title: "Junior Computer Science Student at Texas A&M"
email: chase.mcdermott12@gmail.com
twitter_username: bigc1745
github_username:  chase1745
gplus_username:  chase.mcdermott12

# Google-analytics
google-analytics:
  id: "UA-97580319-1"

exclude: ['package.json', 'src' , 'node_modules']
