# Site settings
title: "Chase McDermott's Website"
description: "Welcome to Chase McDermott's personal website."
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://chase1745.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
author: "Chase McDermott"
# User settings
username: Chase McDermott
baseurl: ""
user_title: "Full-Stack Software Engineer at RetailMeNot"
email: chase.mcdermott12@gmail.com
twitter_username: bigc1745
github_username:  chase1745
gplus_username:  chase.mcdermott12

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

# Google-analytics
google-analytics:
  id: "UA-97580319-1"

exclude: ['package.json', 'src' , 'node_modules']
